spring:
  application:
    name: folder-config

  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///workspace/native-config

server:
  port: 8888